/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RPGBook;

public classjogop {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(newjogop().getGreeting());
    }
}
